### ISSUE TITLE
Topics with `.` separators cannot be used with name format placeholder

### ISSUE THREAD

**Issue by NJAldwin** [aiven/aiven-kafka-connect-jdbc#31]
The `table.name.format` configuration is unfortunately limited.  It cannot currently be used with `.`-separated topics, as it does a straight string replace:
https://github.com/aiven/aiven-kafka-connect-jdbc/blob/master/src/main/java/io/aiven/connect/jdbc/sink/JdbcDbWriter.java#L85-L93

Given a topic name of e.g. `this.is.a.test.topic` and a name format of `kafka_${topic}`, the connector attempts to create the table as `kafka_this.is.a.test.topic`.  In SQL, dot separators are used to specify qualification, so that is parsed as a schema `kafka_this` with a table name `is`.  Here's an example log output:
```
[kafka-connect][2020-05-12 21:31:33,177] INFO Creating table with sql: CREATE TABLE "kafka_this"."is" (
[kafka-connect]"pk" TEXT NOT NULL,
[kafka-connect]PRIMARY KEY("pk")) (io.aiven.connect.jdbc.sink.DbStructure:95)
[kafka-connect]Position: 14
[kafka-connect][2020-05-12 21:31:33,183] WARN Create failed, will attempt amend if table already exists (io.aiven.connect.jdbc.sink.DbStructure:66)
```

Suggested solutions for this:
- specify a replacement that will occur, e.g. all non-`/-A-Za-z0-9_/` characters will be replaced with `_` -- note that the Snowflake connector replaces with `_`s
- allow a separate configuration parameter specifying a topic -> table mapping -- note that the Snowflake connector has a `topic2table.map` parameter that takes a set of `topic:table,` mappings and uses that

Please address this soon.  It is quite common to use dot-separated kafka topics, and this is preventing us from effectively using the connector.

**Comment by willyborankin** [comment]
Hi Nick, first of all sorry for the late response and thank you for the investigation and possible solutions. 
Both solutions look good, so I added 2 new issues: #35 and #36 . RP for #35 has been created since it looks simple to implement, while for the second solution it will take some time.
