### ISSUE TITLE
[Source Connector] Epoch and earlier timestamps are not supported

### ISSUE THREAD

**Issue by NJAldwin** [aiven/aiven-kafka-connect-jdbc#51]
When the connector starts up for the first time (no known offsets), it sets the timestamp offset to `Timestamp(0)`:

https://github.com/aiven/aiven-kafka-connect-jdbc/blob/31e82df8973eda3587bea7d710e2702f68a3908a/src/main/java/io/aiven/connect/jdbc/source/TimestampIncrementingOffset.java#L54

This number is used when building the `WHERE` part of the query:

https://github.com/aiven/aiven-kafka-connect-jdbc/blob/f4ad9b3974cba4e3eae64d01dc726f3cea360992/src/main/java/io/aiven/connect/jdbc/source/TimestampIncrementingCriteria.java#L326-L334

This means that there seems to be no way to load data from a table with timestamps either _before_ the epoch or **equal to the epoch**.

## Potential Fixes

- provide the ability to configure the default starting timestamp (along with a note that it's **exclusive**)
- default the timestamp to a reasonably negative value (note: the absolute minimum timestamp seems to vary by database, per https://stackoverflow.com/a/37144420/134502 -- so it might be hard to choose a value here); this would be a breaking change, so if needed, having it be configurable would be reasonable.
- default the timestamp to `Timestamp(-1)`.  this would _not_ fix the issue of pre-epoch timestamps, but it would at least get rid of the unexpected behavior of omitting epoch values. again, this would be a breaking change, so having it be configurable might be nice.
- fix the logic to use `>=` (this seems less feasible as it would require a change to what "offset" means, and it still wouldn't solve the pre-epoch issue

I'll note the docs are a little misleading on this too. They say:

> The first execution will fetch all available records (i.e. starting at timestamp 0)

which implies inclusivity.  They should say (currently):

> The first execution will fetch all available records (i.e. starting **after** timestamp 0)

**Comment by davidespo** [comment]
Could you confirm your use case? Do you need access to dates before the epoch? Or are you just pointing out that the epoch timestamps are excluded?

**Comment by NJAldwin** [comment]
For our use case, we don't expect to need access to dates _before_ the epoch, however we do have a significant portion of our records (roughly 2/3rds at the current time) which have timestamps that default to the epoch (as they have been imported from earlier systems lacking timestamps).  Thus, for our particular case here, we need to be able to consume records with dates _at_ the epoch.

That being said, I cannot speak to our future use cases; I can't guarantee we won't need to be able to see older records as well in other tables in the future.

**Comment by NJAldwin** [comment]
Any updates on this?  For the time being, we are using a workaround in our `query`:

```sql
-- (snowflake sql)
SELECT FIELD_A, FIELD_B, FIELD_C, FIELD_D,
       IFF(UPDATED_AT_UTC = '1970-01-01 00:00:00.000 +0000',
           TIMESTAMPADD(ms, 1, UPDATED_AT_UTC),
           UPDATED_AT_UTC)
         AS UPDATED_AT_UTC
       FROM DB.SCHEMA.TBL
```

But we would prefer that this is fixed at the connector level.

**Comment by ivanyu** [comment]
Hi Nick
We're still thinking what would be the best approach. Will get back to you soon.

**Comment by ivanyu** [comment]
The ability to configure the default starting timestamp seems interesting: it solves yours and potentially other issues, it doesn't break compatibility, it's a bit more flexible than changing the default. We'll implement this.
