### ISSUE TITLE
[Source Connector] ERROR: Graceful stop of task failed

### ISSUE THREAD

**Issue by NJAldwin** [aiven/aiven-kafka-connect-jdbc#58]
For longer polling durations, the task will spend most of its time asleep.  If the task is asleep when it is getting killed, such as when a rebalance is happening or the config is changed, the task is likely not to return within the configured graceful timeout period, instead causing `Graceful stop of task connector_name-0 failed.` errors. 

We suspect this may be leading to some issues we are seeing with connectors seemingly "hanging", (with only the table monitor thread running).

FWIW the confluent connector seems to have also experienced this issue: https://github.com/confluentinc/kafka-connect-jdbc/pull/677

I have a PR with a fix: #59

**Comment by ivanyu** [comment]
Hi @NJAldwin 
A very relevant issue and fix.
We'll check it shortly.

**Comment by ivanyu** [comment]
Done by https://github.com/aiven/aiven-kafka-connect-jdbc/pull/61
