### ISSUE TITLE
How about one topic to multiple tables?

### ISSUE THREAD

**Issue by wefine** [aiven/aiven-kafka-connect-jdbc#65]
Dear all, 
Is there any guides for one topic sourced from multiple tables in a db, and sink to another db?

Thanks!

**Comment by ivanyu** [comment]
Hi @wefine 

Sourcing one topic from multiple tables is not possible now. We might implement this at some point, but a Transformation plugin might be a better place for this.

I hope I understand right what you want to achieve. If gathering all the data in one topic is only for putting them later in one table, will it help if you subscribe the sink connector to multiple topics and set `table.name.format=target-table`?

**Comment by wefine** [comment]
@ivanyu Thanks for your time!

A logic database db1 has 10 tables, such as tb1, tb2... and another database db2 has the same structure with db1. I need to sync db1 to db2, so I use dbz-mysql-connector with 'combine' transform to put all tables of db1 to one topic, but I don't know how to use jdbc-connector to separate them to db2.

Thanks again!
