### ISSUE TITLE
Column order lost when writing Avro topic to JDBC sink

### ISSUE THREAD

**Issue by Oduig** [aiven/aiven-kafka-connect-jdbc#81]
Columns are shuffled around when the JDBC sink creates a table. It would make more sense for the order of columns to be strict, for the following reasons.

1. Having important columns first makes data easier to explore.
2. Using a fixed order makes the table generation process predictable and deterministic.
3. Column order is important for query performance when it comes to the primary key. Even when I specify in pk.fields that the order of my primary key should be A, B, they still come out as B, A in the created table.
4. There is no reason why an arbitrary order is better, when the order is clearly defined in the Avro schema.

The JDBC Sink by Confluent used to have this bug as well, it was [fixed in 5.x.x](https://github.com/confluentinc/kafka-connect-jdbc/pull/787), I believe by using a LinkedHashMap which preserves order.

The relevant lines of code can be found here.
https://github.com/aiven/aiven-kafka-connect-jdbc/blob/master/src/main/java/io/aiven/connect/jdbc/sink/metadata/FieldsMetadata.java#L133

**Comment by willyborankin** [comment]
Thank you for reporting of this issue. We will fix it ASAP.

**Comment by ivanyu** [comment]
Fixed by https://github.com/aiven/aiven-kafka-connect-jdbc/pull/82
